Repository cozystack/cozystack, pull requests merged in 2024-12, with the labels that each got.

#487 Allow specifying mtu for kubeovn daemonset
  packages/system/kubeovn/Makefile
  packages/system/kubeovn/charts/kube-ovn/templates/ovncni-ds.yaml
  packages/system/kubeovn/patches/mtu.diff
Labels: enhancement, size:S, lgtm

#493 Update Cilium v1.16.4
  packages/system/cilium/charts/cilium/Chart.yaml
  packages/system/cilium/charts/cilium/README.md
  packages/system/cilium/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.json
  packages/system/cilium/charts/cilium/templates/cilium-configmap.yaml
  packages/system/cilium/charts/cilium/templates/hubble-relay/serviceaccount.yaml
  packages/system/cilium/charts/cilium/templates/validate.yaml
  packages/system/cilium/charts/cilium/values.schema.json
  packages/system/cilium/charts/cilium/values.yaml
  packages/system/cilium/charts/cilium/values.yaml.tmpl
  packages/system/cilium/images/cilium/Dockerfile
Labels: size:L

#494 Update LINSTOR v1.29.2
  packages/system/piraeus-operator/charts/piraeus/Chart.yaml
  packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
  packages/system/piraeus-operator/charts/piraeus/templates/crds.yaml
  packages/system/piraeus-operator/charts/piraeus/templates/deployment.yaml
Labels: size:M

#495 Update CDI v1.61.0
  packages/system/kubevirt-cdi-operator/templates/cdi-operator.yaml
Labels: size:S

#496 Update KubeVirt v1.4.0
  packages/system/kubevirt-operator/templates/kubevirt-operator.yaml
Labels: enhancement, size:L

#497 Update Talos Linux v1.8.3
  hack/e2e.sh
  packages/core/installer/images/talos/profiles/initramfs.yaml
  packages/core/installer/images/talos/profiles/installer.yaml
  packages/core/installer/images/talos/profiles/iso.yaml
  packages/core/installer/images/talos/profiles/kernel.yaml
  packages/core/installer/images/talos/profiles/metal.yaml
  packages/core/installer/images/talos/profiles/nocloud.yaml
Labels: size:L

#491 add make-generate to pre-commit
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  packages/apps/nats/README.md
  packages/apps/nats/values.schema.json
  packages/apps/postgres/values.schema.json
Labels: documentation, size:M, lgtm

#499 fix dashboard build
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
Labels: size:M, lgtm

#501 MetallB disable frr by default
  packages/system/metallb/values.yaml
Labels: enhancement, size:XS

#503 MetallB enable frr and disable frr-k8s by default
  packages/system/metallb/Makefile
  packages/system/metallb/charts/metallb/charts/frr-k8s/.helmignore
  packages/system/metallb/charts/metallb/charts/frr-k8s/Chart.lock
  packages/system/metallb/charts/metallb/charts/frr-k8s/Chart.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/README.md
  packages/system/metallb/charts/metallb/charts/frr-k8s/charts/crds/.helmignore
  packages/system/metallb/charts/metallb/charts/frr-k8s/charts/crds/Chart.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/charts/crds/README.md
  packages/system/metallb/charts/metallb/charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrconfigurations.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrnodestates.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/NOTES.txt
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/_helpers.tpl
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/controller.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/rbac.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/service-accounts.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/service-monitor.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/templates/webhooks.yaml
  packages/system/metallb/charts/metallb/charts/frr-k8s/values.schema.json
  packages/system/metallb/charts/metallb/charts/frr-k8s/values.yaml
  packages/system/metallb/values.yaml
Labels: size:XXL

#502 Refactor Keycloak
  hack/e2e.sh
  packages/apps/tenant/templates/dashboard-resourcemap.yaml
  packages/apps/tenant/templates/keycloakgroups.yaml
  packages/apps/tenant/templates/kubeconfig.yaml
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: enhancement, size:L

#505 fix kk-configure
  packages/apps/tenant/templates/networkpolicy.yaml
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: size:S, lgtm

#504 Add basic Makefiles for keycloak
  packages/system/keycloak-configure/Makefile
  packages/system/keycloak-operator/Makefile
  packages/system/keycloak/Makefile
Labels: enhancement, size:S

#506 fix keycloak-configure secrets drift
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: size:M, lgtm

#508 fix keycloak secrets drift
  packages/system/keycloak/templates/sts.yaml
Labels: bug, enhancement, size:XS

#509 fix keycloak secrets drift
  packages/system/keycloak/templates/sts.yaml
Labels: bug, size:XS

#500 Prepare release v0.19.0
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M, lgtm

#511 Add Urmanac to adopters
  ADOPTERS.md
Labels: documentation, size:XS, lgtm

#512 Remove unnecessary allow-to-keycloak policy
  packages/apps/tenant/templates/networkpolicy.yaml
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: size:S, lgtm

#514 NATs: fix hardcode, add merge and resolve config
  packages/apps/nats/Chart.yaml
  packages/apps/nats/README.md
  packages/apps/nats/templates/nats.yaml
  packages/apps/nats/values.schema.json
  packages/apps/nats/values.yaml
  packages/apps/versions_map
Labels: size:L, lgtm

#513 Update Kube-OVN v0.13.0
  packages/system/kubeovn/Makefile
  packages/system/kubeovn/charts/kube-ovn/templates/_helpers.tpl
  packages/system/kubeovn/charts/kube-ovn/templates/central-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/controller-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ic-controller-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/kube-ovn-crd.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/monitor-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovn-CR.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovn-CRB.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovn-sa.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovncni-ds.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovsovn-ds.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/pinger-ds.yaml
  packages/system/kubeovn/charts/kube-ovn/values.yaml
  packages/system/kubeovn/images/kubeovn/Dockerfile
  packages/system/kubeovn/patches/mtu.diff
  packages/system/kubeovn/values.yaml
Labels: enhancement, size:XL

#518 Fix EndpointSlice reconciliation
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider/Dockerfile
  packages/apps/kubernetes/images/kubevirt-cloud-provider/patches/335.diff
  packages/apps/kubernetes/images/kubevirt-cloud-provider/patches/336.diff
  packages/apps/kubernetes/images/kubevirt-cloud-provider/patches/external-traffic-policy-local.diff
  packages/apps/versions_map
Labels: size:XXL

#515 fix kubeconfig
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/kubeconfig.yaml
  packages/apps/versions_map
Labels: size:XS, lgtm

#520 Fix kube-state-mterics and flux alerts labels
  packages/system/monitoring-agents/alerts/flux.yaml
  packages/system/monitoring-agents/templates/kube-state-metrics-scrape.yaml
Labels: size:S

#517 Add cozystack-cluster-admin
  packages/system/keycloak-configure/templates/configure-kk.yaml
  packages/system/keycloak-configure/templates/rolebinding.yaml
  packages/system/keycloak-configure/templates/roles.yaml
Labels: enhancement, size:L, lgtm

#522 Prepare release v0.20.0
  hack/e2e.sh
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
  scripts/installer.sh
  scripts/migrations/7
  scripts/migrations/8
Labels: size:M

#523 bump monitoring version
  packages/core/installer/values.yaml
  packages/extra/monitoring/Chart.yaml
  packages/extra/versions_map
Labels: size:XS

#524 Fix Terraform compatibility
  pkg/apis/apps/v1alpha1/register.go
  pkg/cmd/server/start.go
Labels: size:XS

#525 fix disable oidc
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
Labels: size:XS, lgtm

#526 Fix API resource for Redis
  packages/system/cozystack-api/templates/configmap.yaml
Labels: size:XS

#527 add annotations for fixing 502 status code
  packages/system/dashboard/values.yaml
Labels: bug, size:XS, lgtm

#528 Add redis auth
  packages/apps/redis/Chart.yaml
  packages/apps/redis/README.md
  packages/apps/redis/templates/dashboard-resourcemap.yaml
  packages/apps/redis/templates/redisfailover.yaml
  packages/apps/redis/values.schema.json
  packages/apps/redis/values.yaml
  packages/apps/versions_map
Labels: enhancement, size:M, lgtm

#535 delete-cpu-limit
  packages/extra/monitoring/templates/vm/vmcluster.yaml
Labels: size:XS, lgtm

#534 Refactor tenant RBAC rules
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/tenant.yaml
  packages/apps/versions_map
Labels: size:L

#533 Update kubeapps v2.12.0
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
  packages/system/dashboard/images/kubeapps-apis/dashboard-resource.diff
  packages/system/dashboard/images/kubeapps-apis/fluxcd.diff
  packages/system/dashboard/images/kubeapps-apis/labels.diff
  packages/system/dashboard/images/kubeapps-apis/reconcile-strategy.diff
  packages/system/dashboard/values.yaml
Labels: size:L

#536 add grafana size configure
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/README.md
  packages/extra/monitoring/templates/grafana/db.yaml
  packages/extra/monitoring/values.schema.json
  packages/extra/monitoring/values.yaml
  packages/extra/versions_map
Labels: enhancement, size:M, lgtm

#537 fix logs
  packages/apps/kubernetes/templates/helmreleases/monitoring-agents.yaml
  packages/system/monitoring-agents/values.yaml
Labels: size:M, lgtm

#539 Update dashboard to use Cozystack API
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/tenant.yaml
  packages/apps/versions_map
  packages/system/cozystack-api/templates/configmap.yaml
  packages/system/dashboard/Makefile
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/images/dashboard/documentation.diff
  packages/system/dashboard/images/dashboard/release-url.diff
  packages/system/dashboard/images/dashboard/remove-manage-repositories.diff
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
  packages/system/dashboard/images/kubeapps-apis/dashboard-resource.diff
  packages/system/dashboard/images/kubeapps-apis/dockerfile.diff
  packages/system/dashboard/images/kubeapps-apis/fluxcd.diff
  packages/system/dashboard/images/kubeapps-apis/labels.diff
  packages/system/dashboard/images/kubeapps-apis/reconcile-strategy.diff
  packages/system/dashboard/values.yaml
Labels: enhancement, size:XL

#542 Fix cozystack-api to show correct List types in openapi
  packages/system/cozystack-api/values.yaml
  pkg/cmd/server/start.go
Labels: size:M

#543 Remove kubeapps-admin role
  packages/system/keycloak-configure/templates/configure-kk.yaml
  packages/system/keycloak-configure/templates/rolebinding.yaml
  packages/system/keycloak-configure/templates/roles.yaml
Labels: size:M

#544 update Talos Linux v1.8.4
  hack/e2e.sh
  packages/core/installer/images/talos/profiles/initramfs.yaml
  packages/core/installer/images/talos/profiles/installer.yaml
  packages/core/installer/images/talos/profiles/iso.yaml
  packages/core/installer/images/talos/profiles/kernel.yaml
  packages/core/installer/images/talos/profiles/metal.yaml
  packages/core/installer/images/talos/profiles/nocloud.yaml
  packages/core/testing/images/e2e-sandbox/Dockerfile
  packages/core/testing/values.yaml
Labels: size:L

#545 hardcode vlogs version
  packages/extra/monitoring/templates/grafana/grafana.yaml
Labels: size:XS

#547 fix linstor-ha-controller
  packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
Labels: size:XS

#546 Prepare release v0.21.0
  manifests/cozystack-installer.yaml
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/images/dashboard/documentation.diff
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#548 Update vm-instance to not include vm-disk prefix
  packages/apps/versions_map
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/templates/vm.yaml
  packages/apps/vm-instance/values.yaml
Labels: size:S

#549 Fix tenant permissions for oidc disabled cluster
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/tenant.yaml
  packages/apps/versions_map
Labels: size:XS

#552 disable node.kubernetes.io/exclude-from-external-load-balancers label
  hack/e2e.sh
Labels: size:XS

#551 Prepare release v0.21.1
  manifests/cozystack-installer.yaml
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M
