Repository cozystack/cozystack, pull requests merged in 2024-10, with the labels that each got.

#451 Add tests refactor
  .pre-commit-config.yaml
  hack/e2e.application.sh
  hack/values/tenant.yaml
  packages/apps/ferretdb/templates/init-script.yaml
  packages/core/testing/Chart.yaml
  packages/core/testing/Makefile
  packages/core/testing/images/e2e-sandbox/Dockerfile
  packages/core/testing/templates/sandbox.yaml
  packages/core/testing/values.yaml
Labels: enhancement, size:L, lgtm

#453 Update cozystack-installer.yaml
  manifests/cozystack-installer.yaml
Labels: size:XS, lgtm

#455 add migration for dv
  scripts/installer.sh
  scripts/migrations/5
Labels: size:S, lgtm

#457 fix alerta webhook url
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/templates/alerta/alerta.yaml
  packages/extra/versions_map
Labels: size:S, lgtm
