Repository cozystack/cozystack, pull requests merged in 2024-11, with the labels that each got.

#460 Introduce Cozystack API
  api/api-rules/cozystack_api_violation_exceptions.list
  cmd/cozystack-api/main.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/update-codegen.sh
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/cozystack-api/Chart.yaml
  packages/system/cozystack-api/Makefile
  packages/system/cozystack-api/images/cozystack-api/Dockerfile
  packages/system/cozystack-api/images/cozystack-api/Dockerfile.dockerignore
  packages/system/cozystack-api/templates/apiservice.yaml
  packages/system/cozystack-api/templates/auth-delegator.yaml
  packages/system/cozystack-api/templates/auth-reader.yaml
  packages/system/cozystack-api/templates/configmap.yaml
  packages/system/cozystack-api/templates/deployment.yaml
  packages/system/cozystack-api/templates/rbac-bind.yaml
  packages/system/cozystack-api/templates/rbac.yaml
  packages/system/cozystack-api/templates/sa.yaml
  packages/system/cozystack-api/templates/service.yaml
  packages/system/cozystack-api/values.yaml
  pkg/apis/apps/fuzzer/fuzzer.go
  pkg/apis/apps/install/install.go
  pkg/apis/apps/install/roundtrip_test.go
  pkg/apis/apps/register.go
  pkg/apis/apps/v1alpha1/doc.go
  pkg/apis/apps/v1alpha1/register.go
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.conversion.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.defaults.go
  pkg/apis/apps/validation/validation.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/scheme_test.go
  pkg/cmd/server/start.go
  pkg/cmd/server/start_test.go
  pkg/config/config.go
  pkg/generated/applyconfiguration/apps/v1alpha1/application.go
  pkg/generated/applyconfiguration/apps/v1alpha1/applicationspec.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/applyconfiguration/utils.go
  pkg/generated/listers/apps/v1alpha1/application.go
  pkg/generated/listers/apps/v1alpha1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/apps/application/rest.go
  pkg/registry/registry.go
Labels: enhancement, size:XXL

#459 fix logos names
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/logos/vmi.svg
  scripts/installer.sh
Labels: size:XS, lgtm

#454 add values and checks
  hack/e2e.application.sh
  hack/testdata/kubernetes/check.sh
  hack/testdata/kubernetes/values.yaml
  hack/testdata/nats/check.sh
  hack/testdata/nats/values.yaml
  hack/testdata/tenant/check.sh
  hack/testdata/tenant/values.yaml
  packages/core/testing/Makefile
Labels: enhancement, size:L, lgtm

#465 Update LINSTOR v1.29.2
  packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
Labels: size:XS

#467 Revert "Update LINSTOR v1.29.2"
  packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
Labels: size:XS

#468 fix tenant labels
  packages/apps/kubernetes/templates/helmreleases/monitoring-agents.yaml
Labels: size:XS, lgtm

#469 add endpoint for http checks
  hack/testdata/http-cache/check.sh
  hack/testdata/http-cache/values.yaml
Labels: enhancement, size:XS, lgtm

#462 Prepare release v0.18.0
  Makefile
  hack/e2e.sh
  manifests/cozystack-installer.yaml
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/versions_map
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
  pkg/registry/apps/application/rest.go
  scripts/installer.sh
  scripts/migrations/6
Labels: size:M

#476 revert-precommit
  .pre-commit-config.yaml
Labels: size:S, lgtm

#477 add password for nats
  packages/apps/nats/Chart.yaml
  packages/apps/nats/README.md
  packages/apps/nats/templates/nats.yaml
  packages/apps/nats/templates/resourcemap.yaml
  packages/apps/nats/values.schema.json
  packages/apps/nats/values.yaml
  packages/apps/versions_map
  packages/system/nats/values.yaml
Labels: enhancement, size:L, lgtm

#475 add keycloak
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/keycloak/Chart.yaml
  packages/system/keycloak/templates/db.yaml
  packages/system/keycloak/templates/ingress.yaml
  packages/system/keycloak/templates/service-headless.yaml
  packages/system/keycloak/templates/service.yaml
  packages/system/keycloak/templates/sts.yaml
  packages/system/keycloak/values.yaml
  scripts/installer.sh
  scripts/migrations/7
Labels: enhancement, size:L, lgtm

#481 Make keycloak optional for distro bundles
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
Labels: enhancement, size:XS

#484 Fix OpenAPIv2 definitions for dynamic resources
  packages/system/cozystack-api/values.yaml
  pkg/apis/apps/v1alpha1/register.go
  pkg/apiserver/apiserver.go
  pkg/cmd/server/start.go
Labels: size:L

#485 add kk operator and configure
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/keycloak-operator/Chart.yaml
  packages/system/keycloak-operator/Makefile
  packages/system/keycloak-operator/charts/keycloak-operator/.helmignore
  packages/system/keycloak-operator/charts/keycloak-operator/Chart.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/README.md
  packages/system/keycloak-operator/charts/keycloak-operator/README.md.gotmpl
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/clusterkeycloak.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/clusterkeycloakrealm.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloak.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakauthflow.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakclient.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakclientscope.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealm.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmcomponent.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmgroup.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmidentityprovider.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmrole.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmrolebatch.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmuser.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/_crd_examples/keycloakrealmuser_password.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_clusterkeycloakrealms.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_clusterkeycloaks.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakauthflows.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakclients.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakclientscopes.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmcomponents.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmgroups.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmrolebatches.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmroles.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealms.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloakrealmusers.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/crds/v1.edp.epam.com_keycloaks.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/_helpers.tpl
  packages/system/keycloak-operator/charts/keycloak-operator/templates/clusterrole.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/clusterrolebinding.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/deployment.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/leader_election_role.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/leader_election_rolebinding.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/operator_role.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/operator_rolebinding.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/templates/serviceaccount.yaml
  packages/system/keycloak-operator/charts/keycloak-operator/values.yaml
  packages/system/keycloak-operator/templates/configure-kk.yaml
  packages/system/keycloak/templates/sts.yaml
Labels: enhancement, size:XXL, lgtm
