Repository cozystack/cozystack, pull requests merged in 2025-01, with the labels that each got.

#555 up vmagent limit
  packages/system/monitoring-agents/templates/vmagent.yaml
Labels: size:XS, lgtm

#561 Fix cluster-autoscaler
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/cluster-autoscaler/Dockerfile
  packages/apps/kubernetes/images/cluster-autoscaler/fix-downscale.diff
  packages/apps/kubernetes/templates/cluster-autoscaler/deployment.yaml
Labels: size:S

#560 Introduce cozystack-controller
  Makefile
  api/api-rules/cozystack_api_violation_exceptions.list
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/workload_types.go
  api/v1alpha1/workloadmonitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/cozystack-api/main.go
  cmd/cozystack-controller/main.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/update-codegen.sh
  internal/controller/suite_test.go
  internal/controller/workloadmonitor_controller.go
  internal/telemetry/collector.go
  internal/telemetry/config.go
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/cozystack-api/images/cozystack-api/Dockerfile
  packages/system/cozystack-api/templates/deployment.yaml
  packages/system/cozystack-controller/.gitignore
  packages/system/cozystack-controller/Chart.yaml
  packages/system/cozystack-controller/Makefile
  packages/system/cozystack-controller/images/cozystack-controller/Dockerfile
  packages/system/cozystack-controller/templates/crds/cozystack.io_workloadmonitors.yaml
  packages/system/cozystack-controller/templates/crds/cozystack.io_workloads.yaml
  packages/system/cozystack-controller/templates/deployment.yaml
  packages/system/cozystack-controller/templates/rbac-bind.yaml
  packages/system/cozystack-controller/templates/rbac.yaml
  packages/system/cozystack-controller/templates/sa.yaml
  packages/system/cozystack-controller/values.yaml
  pkg/apis/apps/fuzzer/fuzzer.go
  pkg/apis/apps/install/install.go
  pkg/apis/apps/install/roundtrip_test.go
  pkg/apis/apps/v1alpha1/doc.go
  pkg/apis/apps/v1alpha1/register.go
  pkg/apis/apps/v1alpha1/zz_generated.conversion.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.defaults.go
  pkg/apis/apps/validation/validation.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/scheme_test.go
  pkg/cmd/server/start.go
  pkg/generated/applyconfiguration/apps/v1alpha1/application.go
  pkg/generated/applyconfiguration/utils.go
  pkg/generated/listers/apps/v1alpha1/application.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/apps/application/rest.go
  pkg/registry/registry.go
Labels: enhancement, size:XXL

#564 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation, size:S, lgtm

#562 Update cozystack-dashboard to show workload status
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/images/dashboard/apple-touch-icon.png
  packages/system/dashboard/images/dashboard/documentation.diff
  packages/system/dashboard/images/dashboard/favicon-16x16.png
  packages/system/dashboard/images/dashboard/favicon-32x32.png
  packages/system/dashboard/images/dashboard/favicon.ico
  packages/system/dashboard/images/dashboard/mstile-144x144.png
  packages/system/dashboard/images/dashboard/mstile-150x150.png
  packages/system/dashboard/images/dashboard/mstile-310x150.png
  packages/system/dashboard/images/dashboard/mstile-310x310.png
  packages/system/dashboard/images/dashboard/mstile-70x70.png
  packages/system/dashboard/images/dashboard/release-url.diff
  packages/system/dashboard/images/dashboard/remove-manage-repositories.diff
  packages/system/dashboard/images/dashboard/safari-pinned-tab.svg
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
  packages/system/dashboard/values.yaml
Labels: enhancement, size:L

#559 Introduce builder
  packages/core/builder/Chart.yaml
  packages/core/builder/Makefile
  packages/core/builder/config.toml
  packages/core/builder/templates/sandbox.yaml
  packages/core/builder/values.yaml
  packages/core/installer/Makefile
Labels: enhancement, size:L

#568 Update version-map for updated application
  packages/apps/kubernetes/Chart.yaml
  packages/apps/postgres/Chart.yaml
  packages/apps/redis/Chart.yaml
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/extra/etcd/Chart.yaml
  packages/extra/ingress/Chart.yaml
  packages/extra/monitoring/Chart.yaml
  packages/extra/seaweedfs/Chart.yaml
  packages/extra/versions_map
Labels: size:M

#567 Update Flux Operator
  packages/system/fluxcd-operator/charts/flux-operator/Chart.yaml
  packages/system/fluxcd-operator/charts/flux-operator/README.md
  packages/system/fluxcd-operator/charts/flux-operator/templates/crds.yaml
  packages/system/fluxcd/charts/flux-instance/Chart.yaml
  packages/system/fluxcd/charts/flux-instance/README.md
Labels: documentation, size:M, lgtm

#571 Fix openapi spec for cozystack apps
  pkg/cmd/server/start.go
Labels: size:S

#558 add cnpg alerts
  packages/system/postgres-operator/templates/prometheusrule.yaml
Labels: enhancement, size:L, lgtm

#572 enablePodMonitor
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/templates/alerta/alerta-db.yaml
  packages/extra/monitoring/templates/grafana/db.yaml
  packages/extra/versions_map
  packages/system/keycloak/templates/db.yaml
  packages/system/seaweedfs/templates/database.yaml
Labels: size:S

#553 Update Talos v1.9.1
  hack/e2e.sh
  packages/core/installer/images/talos/profiles/initramfs.yaml
  packages/core/installer/images/talos/profiles/installer.yaml
  packages/core/installer/images/talos/profiles/iso.yaml
  packages/core/installer/images/talos/profiles/kernel.yaml
  packages/core/installer/images/talos/profiles/metal.yaml
  packages/core/installer/images/talos/profiles/nocloud.yaml
Labels: enhancement, size:M

#576 Update Cilium v1.16.5
  packages/system/cilium/charts/cilium/Chart.yaml
  packages/system/cilium/charts/cilium/README.md
  packages/system/cilium/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.json
  packages/system/cilium/charts/cilium/templates/hubble-relay/configmap.yaml
  packages/system/cilium/charts/cilium/values.yaml
  packages/system/cilium/images/cilium/Dockerfile
Labels: size:L

#577 Update Kube-OVN v1.13.2
  packages/system/kubeovn/Makefile
  packages/system/kubeovn/charts/kube-ovn/Chart.yaml
  packages/system/kubeovn/charts/kube-ovn/values.yaml
  packages/system/kubeovn/images/kubeovn/Dockerfile
  packages/system/kubeovn/values.yaml
Labels: size:S

#574 fix cnpg alerts templating
  packages/system/postgres-operator/alerts/cnpg-default-alerts.yaml
  packages/system/postgres-operator/templates/alerts.yaml
Labels: size:M

#579 add-extra-redirect-uri
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: enhancement, size:XS

#581 Fix kubevirt monitoring alerts
  packages/system/kubevirt-operator/alerts/PrometheusRule.yaml
Labels: size:XS

#570 Prepare release v0.22.0
  Makefile
  hack/e2e.sh
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#587 bugfix/monitoring add nil checker
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/templates/vm/vmcluster.yaml
  packages/extra/versions_map
Labels: bug, size:S

#586 Update fluxcd-operator to 0.13.0
  packages/system/fluxcd-operator/charts/flux-operator/Chart.yaml
  packages/system/fluxcd-operator/charts/flux-operator/README.md
  packages/system/fluxcd/charts/flux-instance/Chart.yaml
  packages/system/fluxcd/charts/flux-instance/README.md
  packages/system/fluxcd/charts/flux-instance/templates/instance.yaml
  packages/system/fluxcd/charts/flux-instance/values.schema.json
  packages/system/fluxcd/charts/flux-instance/values.yaml
Labels: documentation, enhancement, size:M

#585 feature/add-tg-severity-setting
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/README.md
  packages/extra/monitoring/templates/alerta/alerta.yaml
  packages/extra/monitoring/values.schema.json
  packages/extra/monitoring/values.yaml
  packages/extra/versions_map
Labels: enhancement, size:M

#588 Update Talos Linux v1.9.2
  packages/core/builder/values.yaml
  packages/core/installer/images/talos/profiles/initramfs.yaml
  packages/core/installer/images/talos/profiles/installer.yaml
  packages/core/installer/images/talos/profiles/iso.yaml
  packages/core/installer/images/talos/profiles/kernel.yaml
  packages/core/installer/images/talos/profiles/metal.yaml
  packages/core/installer/images/talos/profiles/nocloud.yaml
Labels: size:M

#589 Bugfix/fix kk configure reconciliation
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
Labels: bug, size:XS

#590 Add hooks to update instanceType, instanceProfile, and storage
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/virtual-machine/templates/vm-update-hook.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/templates/vm-update-hook.yaml
  packages/apps/vm-instance/templates/vm.yaml
Labels: enhancement, size:L

#591 Prepare release v0.23.0
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#592 Fix dashboard error: Unable to get installed package
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/images/kubeapps-apis/Dockerfile
Labels: size:XS

#593 Prepare release v0.23.1
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#594 feature/fix-k8s-config-with-OIDC
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/kubeconfig.yaml
  packages/apps/versions_map
Labels: size:S, lgtm

#598 Fix kamaji make update
  packages/system/kamaji/Makefile
  packages/system/kamaji/charts/kamaji/Chart.lock
  packages/system/kamaji/charts/kamaji/Chart.yaml
  packages/system/kamaji/charts/kamaji/README.md
  packages/system/kamaji/charts/kamaji/crds/kamaji.clastix.io_tenantcontrolplanes.yaml
  packages/system/kamaji/charts/kamaji/templates/controller.yaml
  packages/system/kamaji/charts/kamaji/values.yaml
  packages/system/kamaji/images/kamaji/Dockerfile
Labels: size:M, lgtm

#597 Fix vm-update hook access to api
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/virtual-machine/templates/vm-update-hook.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/templates/vm-update-hook.yaml
Labels: size:S

#601 Introduce BootBox
  packages/core/installer/Makefile
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/extra/bootbox/Chart.yaml
  packages/extra/bootbox/Makefile
  packages/extra/bootbox/README.md
  packages/extra/bootbox/hack/test.sh
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/bootbox/logos/bootbox.svg
  packages/extra/bootbox/templates/check-release-name.yaml
  packages/extra/bootbox/templates/dashboard-resourcemap.yaml
  packages/extra/bootbox/templates/matchbox/configmaps.yaml
  packages/extra/bootbox/templates/matchbox/deployment.yaml
  packages/extra/bootbox/templates/matchbox/ingress.yaml
  packages/extra/bootbox/templates/matchbox/machines.yaml
  packages/extra/bootbox/templates/matchbox/service.yaml
  packages/extra/bootbox/values.schema.json
  packages/extra/bootbox/values.yaml
  packages/extra/versions_map
  packages/system/bootbox/Chart.yaml
  packages/system/bootbox/Makefile
  packages/system/bootbox/charts/smee/Chart.yaml
  packages/system/bootbox/charts/smee/crds/hardware-crd.yaml
  packages/system/bootbox/charts/smee/templates/_ports.tpl
  packages/system/bootbox/charts/smee/templates/_scheduling.tpl
  packages/system/bootbox/charts/smee/templates/deployment.yaml
  packages/system/bootbox/charts/smee/templates/role-binding.yaml
  packages/system/bootbox/charts/smee/templates/role.yaml
  packages/system/bootbox/charts/smee/templates/service-account.yaml
  packages/system/bootbox/charts/smee/templates/service.yaml
  packages/system/bootbox/charts/smee/values.schema.json
  packages/system/bootbox/charts/smee/values.yaml
  packages/system/bootbox/templates/bootbox.yaml
  packages/system/bootbox/values.yaml
  packages/system/cozystack-api/templates/configmap.yaml
  packages/system/dashboard/values.yaml
Labels: enhancement, size:XXL

#596 Replace darkhttpd with cozystack-assets-server
  cmd/cozystack-assets-server/main.go
  packages/core/installer/images/cozystack/Dockerfile
  packages/core/installer/templates/cozystack.yaml
Labels: enhancement, size:M

#607 Update Grafana, build plugins
  Makefile
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/Makefile
  packages/extra/monitoring/images/grafana.tag
  packages/extra/monitoring/images/grafana/Dockerfile
  packages/extra/monitoring/templates/grafana/grafana.yaml
  packages/extra/versions_map
Labels: enhancement, size:M

#606 Prepare release v0.24.0
  manifests/cozystack-installer.yaml
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#610 Revert kamaji edge-24.12.1
  packages/system/kamaji/charts/kamaji/Chart.lock
  packages/system/kamaji/charts/kamaji/Chart.yaml
  packages/system/kamaji/charts/kamaji/README.md
  packages/system/kamaji/charts/kamaji/crds/kamaji.clastix.io_tenantcontrolplanes.yaml
  packages/system/kamaji/charts/kamaji/templates/controller.yaml
  packages/system/kamaji/charts/kamaji/values.yaml
  packages/system/kamaji/images/kamaji/Dockerfile
Labels: size:M

#611 Prepare release v0.24.1
  manifests/cozystack-installer.yaml
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M
