Repository cozystack/cozystack, pull requests merged in 2025-03, with the labels that each got.

#657 VirtualMachine: Fix WholeIP enum check
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/virtual-machine/Makefile
  packages/apps/virtual-machine/values.schema.json
Labels: size:S

#659 Prepare release v0.26.1
  manifests/cozystack-installer.yaml
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#662 Add TL as codeowner
  .github/CODEOWNERS
Labels: size:XS, lgtm

#661 feature/add-ch-dashboard
  dashboards/clickhouse/altinity-clickhouse-operator-dashboard.json
  packages/extra/monitoring/dashboards.list
  packages/system/clickhouse-operator/values.yaml
Labels: enhancement, size:XS, lgtm

#663 bugfix/mv-ds-var-for-goldpinger
  dashboards/goldpinger/goldpinger.json
Labels: size:XXL, lgtm

#664 feature/change-severity-for-kube-client-certificate-expiration
  packages/system/monitoring-agents/alerts/kubernetes-system-apiserver.yaml
Labels: enhancement, size:XS, lgtm

#666 CAPI-operator: Remove the invalid caBundle
  packages/system/capi-operator/charts/cluster-api-operator/templates/operator-components.yaml
Labels: size:XS, lgtm

#665 Fix regression for updating Kamaji
  packages/system/kamaji/charts/kamaji/Chart.lock
  packages/system/kamaji/charts/kamaji/Chart.yaml
  packages/system/kamaji/charts/kamaji/README.md
  packages/system/kamaji/charts/kamaji/crds/kamaji.clastix.io_tenantcontrolplanes.yaml
  packages/system/kamaji/charts/kamaji/templates/controller.yaml
  packages/system/kamaji/charts/kamaji/values.yaml
Labels: bug, size:M, lgtm

#658 Import Piraeus dashboard and alerts.
  dashboards/storage/linstor.json
  packages/extra/monitoring/dashboards.list
  packages/system/linstor/templates/podscrape.yaml
  packages/system/piraeus-operator/alerts/piraeus-datastore.yaml
  packages/system/piraeus-operator/templates/alerts.yaml
Labels: enhancement, size:XXL, lgtm

#667 Update Cluster-API and providers
  packages/system/capi-operator/charts/cluster-api-operator/Chart.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/addon.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/bootstrap.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/control-plane.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/core-conditions.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/core.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/deployment.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/infra-conditions.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/infra.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/ipam.yaml
  packages/system/capi-operator/charts/cluster-api-operator/templates/operator-components.yaml
  packages/system/capi-operator/charts/cluster-api-operator/values.yaml
  packages/system/capi-providers/templates/providers.yaml
Labels: enhancement, size:L

#668 bump monitoring chart version
  packages/extra/monitoring/Chart.yaml
  packages/extra/versions_map
Labels: size:XS

#669 Update cozy-proxy v0.1.3
  packages/system/cozy-proxy/charts/cozy-proxy/Chart.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/templates/daemonset.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/values.yaml
Labels: size:XS

#670 Update etcd-operator v0.4.1
  packages/system/etcd-operator/charts/etcd-operator/Chart.yaml
  packages/system/etcd-operator/charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
Labels: size:XS

#673 Kubernetes: fix namespace for KubevirtMachineTemplate
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/templates/cluster.yaml
  packages/apps/versions_map
Labels: bug, size:XS

#674 Patch kamaji to hardcode ControlplaneEndpoint port
  packages/system/kamaji/images/kamaji/patches/hardcode-port.diff
Labels: size:S, lgtm

#672 Add linstor plunger scripts as sidecars
  packages/system/linstor/hack/plunger/plunger-controller.sh
  packages/system/linstor/hack/plunger/plunger-satellite.sh
  packages/system/linstor/templates/_helpers.tpl
  packages/system/linstor/templates/cluster.yaml
  packages/system/linstor/templates/plunger/configmap-scripts.yaml
  packages/system/linstor/templates/plunger/configmap.yaml
  packages/system/linstor/templates/plunger/plunger.yaml
  packages/system/linstor/templates/satellites-cozy.yaml
  packages/system/linstor/templates/satellites-plunger.yaml
  packages/system/linstor/templates/satellites-talos.yaml
Labels: enhancement, size:L, lgtm

#675 Recreate etcd pods and certificates on update
  packages/extra/etcd/Chart.yaml
  packages/extra/etcd/templates/hook/job.yaml
  packages/extra/etcd/templates/hook/role.yaml
  packages/extra/etcd/templates/hook/rolebinding.yaml
  packages/extra/etcd/templates/hook/serviceaccount.yaml
  packages/extra/etcd/templates/version.yaml
  packages/extra/versions_map
Labels: enhancement, size:M, lgtm

#678 Prepare release v0.27.0
  manifests/cozystack-installer.yaml
  packages/apps/clickhouse/images/clickhouse-backup.tag
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M, lgtm

#683 kubeovn v1.13.3
  packages/system/kubeovn/charts/kube-ovn/Chart.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/controller-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/monitor-deploy.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovn-CR.yaml
  packages/system/kubeovn/charts/kube-ovn/templates/ovncni-ds.yaml
  packages/system/kubeovn/charts/kube-ovn/values.yaml
  packages/system/kubeovn/values.yaml
Labels: enhancement, size:XL

#681 Update Flux Operator
  packages/system/fluxcd-operator/charts/flux-operator/Chart.yaml
  packages/system/fluxcd-operator/charts/flux-operator/README.md
  packages/system/fluxcd-operator/charts/flux-operator/templates/crds.yaml
  packages/system/fluxcd-operator/charts/flux-operator/templates/deployment.yaml
  packages/system/fluxcd-operator/charts/flux-operator/values.schema.json
  packages/system/fluxcd-operator/charts/flux-operator/values.yaml
  packages/system/fluxcd/charts/flux-instance/Chart.yaml
  packages/system/fluxcd/charts/flux-instance/README.md
  packages/system/fluxcd/charts/flux-instance/templates/instance.yaml
  packages/system/fluxcd/charts/flux-instance/values.schema.json
  packages/system/fluxcd/charts/flux-instance/values.yaml
Labels: documentation, size:M
