Repository cozystack/cozystack, pull requests merged in 2025-06, with the labels that each got.

#1031 [cozystack-controller] Fix RBAC for annotating namespaces
  packages/system/cozystack-controller/templates/rbac.yaml
Labels: backport

#1020 [Fix] CloudInit for VM Instance
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/templates/vm.yaml
Labels: ok-to-test

#1040 [kafka] specify mimimal working resource presets
  packages/apps/kafka/Chart.yaml
  packages/apps/kafka/README.md
  packages/apps/kafka/values.schema.json
  packages/apps/kafka/values.yaml
  packages/apps/versions_map
Labels: backport

#1051 [bugfix] add-resource-quotas-for-pg-jobs-and-fix-install-generate
  .github/workflows/pre-commit.yml
  hack/e2e-cluster.bats
  packages/apps/postgres/Chart.yaml
  packages/apps/postgres/templates/_postgresjobs.tpl
  packages/apps/postgres/templates/backup-cronjob.yaml
  packages/apps/postgres/templates/init-job.yaml
  packages/apps/versions_map
Labels: backport

#1054 [platform] decrease resources for system applications
  packages/extra/monitoring/Chart.yaml
  packages/extra/monitoring/templates/vpa.yaml
  packages/extra/seaweedfs/Chart.yaml
  packages/extra/seaweedfs/templates/vpa.yaml
  packages/extra/versions_map
  packages/system/dashboard/values.yaml
  packages/system/fluxcd-operator/values.yaml
  packages/system/kubeovn/values.yaml
Labels: backport

#1056 [bugfix] fix distro full bundle
  packages/core/platform/bundles/distro-full.yaml
  packages/system/snapshot-controller/template/clusterissuer.yaml
Labels: backport

#1097 [tests] increase disk space for vms
  hack/e2e-cluster.bats
Labels: backport

#1091 Make VMAgent extraArgs tunable
  packages/system/monitoring-agents/templates/vmagent.yaml
  packages/system/monitoring-agents/values.yaml
Labels: ok-to-test, backport

#1125 [cozy-lib, bug] divf by cpu ratio, not mulf
  packages/library/cozy-lib/templates/_resourcepresets.tpl
  packages/library/cozy-lib/templates/_resources.tpl
Labels: do-not-merge
