Repository cozystack/cozystack, pull requests merged in 2025-02, with the labels that each got.

#612 Rebiild matchobx
  packages/extra/bootbox/images/matchbox.tag
Labels: size:XS

#613 feature/add-client-etcd-monitoring
  dashboards/control-plane/kube-etcd.json
  dashboards/control-plane/kube-etcd3.json
  hack/download-dashboards.sh
  packages/extra/etcd/Chart.yaml
  packages/extra/etcd/templates/etcd-cluster.yaml
  packages/extra/etcd/templates/podscrape.yaml
  packages/extra/etcd/templates/prometheus-rules.yaml
  packages/extra/monitoring/dashboards.list
  packages/extra/versions_map
Labels: enhancement, size:XXL, lgtm

#615 Introduce cozy-proxy
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/system/cozy-proxy/Chart.yaml
  packages/system/cozy-proxy/Makefile
  packages/system/cozy-proxy/charts/cozy-proxy/Chart.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/templates/_helpers.tpl
  packages/system/cozy-proxy/charts/cozy-proxy/templates/daemonset.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/templates/role.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/templates/rolebinding.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/templates/serviceaccount.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/values.yaml
  packages/system/cozy-proxy/values.yaml
Labels: enhancement, size:L

#614 feature/add-etcd-vm-node-scrape
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/distro-hosted.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/monitoring-agents/templates/etcd-proxy-scrape.yaml
  packages/system/monitoring-agents/templates/etcd-scrape.yaml
  packages/system/monitoring-agents/values.yaml
Labels: enhancement, size:L, lgtm

#619 feature/add-flux-dashboards
  dashboards/flux/flux-control-plane.json
  dashboards/flux/flux-stats.json
  hack/download-dashboards.sh
  packages/extra/monitoring/dashboards.list
Labels: enhancement, size:XXL, lgtm

#618 Update cilium v1.16.6
  packages/system/cilium/charts/cilium/Chart.yaml
  packages/system/cilium/charts/cilium/README.md
  packages/system/cilium/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.json
  packages/system/cilium/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.yaml
  packages/system/cilium/charts/cilium/templates/cilium-agent/daemonset.yaml
  packages/system/cilium/charts/cilium/templates/cilium-configmap.yaml
  packages/system/cilium/charts/cilium/templates/cilium-envoy/configmap.yaml
  packages/system/cilium/charts/cilium/templates/hubble-ui/_nginx.tpl
  packages/system/cilium/charts/cilium/values.yaml
  packages/system/cilium/images/cilium/Dockerfile
Labels: size:XL

#616 Introduce externalMethod=WholeIP for VMs
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/virtual-machine/Makefile
  packages/apps/virtual-machine/README.md
  packages/apps/virtual-machine/templates/service.yaml
  packages/apps/virtual-machine/values.schema.json
  packages/apps/virtual-machine/values.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/Makefile
  packages/apps/vm-instance/README.md
  packages/apps/vm-instance/templates/service.yaml
  packages/apps/vm-instance/values.schema.json
  packages/apps/vm-instance/values.yaml
Labels: enhancement, size:M

#617 Update Talos v1.9.3
  packages/core/builder/values.yaml
  packages/core/installer/images/talos/profiles/initramfs.yaml
  packages/core/installer/images/talos/profiles/installer.yaml
  packages/core/installer/images/talos/profiles/iso.yaml
  packages/core/installer/images/talos/profiles/kernel.yaml
  packages/core/installer/images/talos/profiles/metal.yaml
  packages/core/installer/images/talos/profiles/nocloud.yaml
Labels: size:M

#624 Update cozy-proxy v0.1.1
  packages/system/cozy-proxy/Chart.yaml
  packages/system/cozy-proxy/charts/cozy-proxy/values.yaml
Labels: size:XS

#622 Prepare release v0.25.0
  Makefile
  manifests/cozystack-installer.yaml
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#630 Prepare release v0.25.1
  manifests/cozystack-installer.yaml
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/versions_map
  packages/core/installer/Makefile
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#626 feature/add-workloadmonitors-roles
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/tenant.yaml
  packages/apps/versions_map
Labels: enhancement, size:M, lgtm

#634 Prepare release v0.25.2
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/capi-providers/templates/providers.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/images/dashboard/Dockerfile
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/keycloak-operator/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M

#638 feature/mv-kubeconfig
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/info.yaml
  packages/apps/tenant/templates/tenant.yaml
  packages/apps/versions_map
  packages/extra/info/.helmignore
  packages/extra/info/Chart.yaml
  packages/extra/info/Makefile
  packages/extra/info/README.md
  packages/extra/info/logos/info.svg
  packages/extra/info/templates/dashboard-resourcemap.yaml
  packages/extra/info/templates/kubeconfig.yaml
  packages/extra/info/values.schema.json
  packages/extra/info/values.yaml
  packages/extra/versions_map
  packages/system/cozystack-api/templates/configmap.yaml
  packages/system/dashboard/values.yaml
Labels: enhancement, size:L

#642 Prepare release v0.25.3
  manifests/cozystack-installer.yaml
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
Labels: size:S

#633 Update kamaji version
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/templates/cluster.yaml
  packages/apps/versions_map
  packages/system/kamaji/charts/kamaji/Chart.lock
  packages/system/kamaji/images/kamaji/Dockerfile
  scripts/installer.sh
  scripts/migrations/8
  scripts/migrations/9
Labels: enhancement, size:S, lgtm

#647 Allow lookup function in 'make diff'.
  scripts/package.mk
Labels: enhancement, size:XS, lgtm

#648 feature/add-goldpinger
  dashboards/goldpinger/goldpinger.json
  hack/download-dashboards.sh
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/extra/monitoring/dashboards.list
  packages/system/goldpinger/Chart.yaml
  packages/system/goldpinger/Makefile
  packages/system/goldpinger/charts/goldpinger/.helmignore
  packages/system/goldpinger/charts/goldpinger/Chart.yaml
  packages/system/goldpinger/charts/goldpinger/templates/_helpers.tpl
  packages/system/goldpinger/charts/goldpinger/templates/clusterrole.yaml
  packages/system/goldpinger/charts/goldpinger/templates/clusterrolebinding.yaml
  packages/system/goldpinger/charts/goldpinger/templates/configmap.yaml
  packages/system/goldpinger/charts/goldpinger/templates/daemonset.yaml
  packages/system/goldpinger/charts/goldpinger/templates/ingress.yaml
  packages/system/goldpinger/charts/goldpinger/templates/prometheusrule.yaml
  packages/system/goldpinger/charts/goldpinger/templates/role.yaml
  packages/system/goldpinger/charts/goldpinger/templates/rolebinding.yaml
  packages/system/goldpinger/charts/goldpinger/templates/service.yaml
  packages/system/goldpinger/charts/goldpinger/templates/serviceaccount.yaml
  packages/system/goldpinger/charts/goldpinger/templates/servicemonitor.yaml
  packages/system/goldpinger/charts/goldpinger/values.yaml
  packages/system/goldpinger/values.yaml
Labels: enhancement, size:XXL, lgtm

#620 Improve TLS handling in etcd helm chart
  packages/extra/etcd/Chart.yaml
  packages/extra/etcd/templates/etcd-cluster.yaml
  packages/extra/etcd/values.schema.json
  packages/extra/versions_map
Labels: enhancement, size:M, lgtm

#644 feature/add-quota
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/README.md
  packages/apps/tenant/templates/quota.yaml
  packages/apps/tenant/values.schema.json
  packages/apps/tenant/values.yaml
  packages/apps/versions_map
Labels: documentation, enhancement, size:M, lgtm

#643 bugfix/fix-nil-pointer
  packages/core/platform/bundles/paas-full.yaml
  packages/core/platform/bundles/paas-hosted.yaml
  packages/system/dashboard/values.yaml
  packages/system/keycloak-configure/templates/configure-kk.yaml
Labels: bug, size:M, lgtm

#640 Upgrade to Flux 2.5.0
  packages/system/fluxcd/values.yaml
Labels: enhancement, size:XS, lgtm

#649 Add new info logo in common style
  packages/extra/info/logos/info.svg
Labels: size:XS

#653 Upd cilium v1.16.7
  packages/system/cilium/charts/cilium/Chart.yaml
  packages/system/cilium/charts/cilium/README.md
  packages/system/cilium/charts/cilium/files/nodeinit/startup.bash
  packages/system/cilium/charts/cilium/templates/cilium-configmap.yaml
  packages/system/cilium/charts/cilium/templates/validate.yaml
  packages/system/cilium/charts/cilium/values.schema.json
  packages/system/cilium/charts/cilium/values.yaml
  packages/system/cilium/charts/cilium/values.yaml.tmpl
  packages/system/cilium/images/cilium/Dockerfile
Labels: size:M, lgtm

#652 kubevirt: Enable live-migration by default
  packages/system/kubevirt/templates/kubevirt-cr.yaml
Labels: enhancement, size:XS, lgtm

#651 linstor: add basic snapshot functionality
  packages/core/platform/bundles/distro-full.yaml
  packages/core/platform/bundles/paas-full.yaml
  packages/system/linstor/templates/plunger/configmap.yaml
  packages/system/linstor/templates/plunger/plunger.yaml
  packages/system/linstor/templates/volumesnapshotclass.yaml
Labels: enhancement, size:M, lgtm

#654 Prepare release v0.26.0
  packages/apps/ferretdb/images/postgres-backup.tag
  packages/apps/http-cache/images/nginx-cache.tag
  packages/apps/kubernetes/images/cluster-autoscaler.tag
  packages/apps/kubernetes/images/kubevirt-cloud-provider.tag
  packages/apps/kubernetes/images/kubevirt-csi-driver.tag
  packages/apps/kubernetes/images/ubuntu-container-disk.tag
  packages/apps/mysql/images/mariadb-backup.tag
  packages/apps/postgres/images/postgres-backup.tag
  packages/core/installer/values.yaml
  packages/core/testing/values.yaml
  packages/extra/bootbox/images/matchbox.tag
  packages/extra/monitoring/images/grafana.tag
  packages/system/bucket/images/s3manager.tag
  packages/system/cilium/values.yaml
  packages/system/cozystack-api/values.yaml
  packages/system/cozystack-controller/values.yaml
  packages/system/dashboard/charts/kubeapps/templates/dashboard/configmap.yaml
  packages/system/dashboard/values.yaml
  packages/system/kamaji/values.yaml
  packages/system/kubeovn/values.yaml
Labels: size:M
