Repository cozystack/cozystack, pull requests merged in 2025-04, with the labels that each got.

#750 Add workflow to run e2e tests using GitHub CI
  .github/workflows/pull-requests.yaml
  .github/workflows/tags.yaml
  Makefile
  hack/e2e.sh
  packages/core/builder/Chart.yaml
  packages/core/builder/Makefile
  packages/core/builder/config.toml
  packages/core/builder/templates/sandbox.yaml
  packages/core/builder/values.yaml
  packages/core/installer/Makefile
  packages/core/testing/Makefile
  packages/core/testing/images/e2e-sandbox/Dockerfile
  packages/core/testing/templates/sandbox.yaml
  packages/core/testing/values.yaml
Labels: ok-to-test

#758 [k8s] change CP default resourcesPreset
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/values.yaml
  packages/apps/versions_map
Labels: ok-to-test

#782 [e2e] Add mirror.gcr.io as default mirror for docker.io
  hack/e2e.sh
Labels: ok-to-test

#646 Add guard against empty cloudInit in vm-instance app
  packages/apps/virtual-machine/README.md
  packages/apps/virtual-machine/templates/vm.yaml
  packages/apps/virtual-machine/values.schema.json
  packages/apps/virtual-machine/values.yaml
  packages/apps/vm-instance/README.md
  packages/apps/vm-instance/templates/vm.yaml
  packages/apps/vm-instance/values.schema.json
  packages/apps/vm-instance/values.yaml
Labels: enhancement, size:M

#811 [platform] Another logic for deleting components
  packages/core/platform/Makefile
  packages/core/platform/templates/helmreleases.yaml
Labels: ok-to-test

#833 [platform] Fix installing HelmReleases on initial setup
  packages/core/platform/templates/helmreleases.yaml
Labels: ok-to-test

#835 [kubernetes] Fix tenant addons removal
  packages/apps/kubernetes/Chart.yaml
  packages/apps/kubernetes/templates/helmreleases/delete.yaml
  packages/apps/versions_map
Labels: backport

#818 [platform] Hash tenant config and store in configmap
  packages/apps/tenant/templates/configuration-hash.yaml
  packages/core/platform/templates/apps.yaml
  packages/core/platform/templates/configuration-hash.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/registry/apps/application/rest.go
Labels: ok-to-test

#846 Update LINSTOR to v1.31.0
  packages/system/piraeus-operator/charts/piraeus/Chart.yaml
  packages/system/piraeus-operator/charts/piraeus/templates/config.yaml
Labels: ok-to-test

#808 [kubevirt] Enable VMExport feature
  packages/extra/ingress/Chart.yaml
  packages/extra/ingress/README.md
  packages/extra/ingress/values.schema.json
  packages/extra/ingress/values.yaml
  packages/extra/ingress/vm-exportproxy.yaml
  packages/extra/versions_map
  packages/system/kubevirt/templates/kubevirt-cr.yaml
Labels: ok-to-test

#841 [ci] Enable release-candidates and backport functionality
  .github/workflows/backport.yaml
  .github/workflows/pull-requests-release.yaml
  .github/workflows/pull-requests.yaml
  .github/workflows/tags.yaml
Labels: backport

#850 [platform]: add vpa for cozy etcd operator
  packages/system/etcd-operator/charts/etcd-operator/Chart.yaml
  packages/system/etcd-operator/charts/etcd-operator/README.md
  packages/system/etcd-operator/charts/etcd-operator/templates/workload/deployment.yml
  packages/system/etcd-operator/charts/etcd-operator/templates/workload/vpa.yml
  packages/system/etcd-operator/charts/etcd-operator/values.schema.json
  packages/system/etcd-operator/charts/etcd-operator/values.yaml
Labels: ok-to-test

#858 [e2e] fix timeouts for capi and keycloak
  hack/e2e.sh
Labels: backport

#854 [tenant] Fix networkpolicy for accessing externalIPs from the cluster
  packages/apps/tenant/Chart.yaml
  packages/apps/tenant/templates/networkpolicy.yaml
  packages/apps/versions_map
Labels: backport

#862 [virtual-machine] Fix: Add GPU names to virtual machines spec
  packages/apps/versions_map
  packages/apps/virtual-machine/Chart.yaml
  packages/apps/virtual-machine/templates/vm.yaml
  packages/apps/vm-instance/Chart.yaml
  packages/apps/vm-instance/templates/vm.yaml
Labels: backport

#872 [postgres] remove douplicated template from backup manifest
  packages/apps/postgres/Chart.yaml
  packages/apps/postgres/templates/backup-cronjob.yaml
  packages/apps/versions_map
Labels: backport

#876 [ci] Fix uploading assets to release
  .github/workflows/tags.yaml
Labels: backport

#882 [ci] Do not run tests in release building pipeline
  .github/workflows/tags.yaml
Labels: backport
